# name: Add Labels

# on:
#   pull_request:
#     types: [opened, synchronize]
#   issues:
#     types: [opened]

# jobs:
#   add_labels:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions-ecosystem/action-add-labels@v1.1.0
#         if: ${{ startsWith(github.event.comment.body, '/documentation') }}
#         with:
#           github_token: ${{ secrets.token }}
#           labels: documentation
#       # - uses: actions-ecosystem/action-add-labels@v1.1.0
#       #   if: ${{ startsWith(github.event.comment.body, '/bug') }}
#       #   with:
#       #     github_token: ${{ secrets.token }}
#       #     labels: bug
#       # - uses: actions-ecosystem/action-add-labels@v1.1.0
#       #   if: ${{ startsWith(github.event.comment.body, '/feature') }}
#       #   with:
#       #     github_token: ${{ secrets.token }}
#       #     labels: feature

# on:
# issues:
#   types: [opened, edited, closed, reopened]
# pull_request:
#   types: [opened, edited, closed, reopened, ready_for_review, synchronize]

# jobs:
#   labeller_test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Add labels
#         id: labeller
#         uses: Videndum/super-labeler-action@v1.0.0
#         with:
#           GITHUB_TOKEN: ${{ secrets.token }}
name: Labeler
on:
  issues:
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [opened, edited, closed, reopened, ready_for_review, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.token }}"
          sync-labels: true